# Generated by Django 5.2.14 on 2026-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feedingstation_volunteerapplication_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalreport",
            options={
                "verbose_name": "Hayvan İlanı",
                "verbose_name_plural": "Hayvan İlanları",
            },
        ),
        migrations.AlterModelOptions(
            name="feedingstation",
            options={
                "verbose_name": "Besleme İstasyonu",
                "verbose_name_plural": "Besleme İstasyonları",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerapplication",
            options={
                "verbose_name": "Gönüllü Başvurusu",
                "verbose_name_plural": "Gönüllü Başvuruları",
            },
        ),
        migrations.AlterField(
            model_name="animalreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("lost", "Kayıp"),
                    ("adoption", "Sahiplendirme"),
                    ("medical", "Medikal Yardım"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animalreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="feedingstation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
